---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://oylenshpeegul.github.io/hugo_gh_blog"
title: "Hugo Blog on GitHub Pages"
canonifyurls: true
...

